
import React from 'react';
import Navbar from '../components/Navbar';
import { Link } from 'react-router-dom';

const LandingPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-dark-900 text-dark-100 font-sans">
      <Navbar />
      <main className="container mx-auto px-4 sm:px-6 lg:p-8 flex flex-col items-center justify-center text-center" style={{ minHeight: 'calc(100vh - 64px)' }}>
        
        <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold text-white mb-4 animate-fade-in-down">
          Unleash Your Potential with an <span className="text-primary">AI Fitness Coach</span>
        </h1>
        
        <p className="max-w-2xl mx-auto text-lg md:text-xl text-dark-200 mb-8 animate-fade-in-up">
          Stop guessing in the gym. Get personalized, data-driven workout plans generated by a cutting-edge AI. Track your progress, stay motivated, and achieve your fitness goals faster than ever.
        </p>
        
        <div className="flex flex-col sm:flex-row items-center space-y-4 sm:space-y-0 sm:space-x-4 animate-fade-in-up" style={{ animationDelay: '0.5s' }}>
          <Link
            to="/register"
            className="w-full sm:w-auto bg-primary text-dark-900 font-bold py-3 px-8 rounded-md hover:bg-primary-dark transition-transform hover:scale-105"
          >
            Get Started for Free
          </Link>
          <Link
            to="/login"
            className="w-full sm:w-auto bg-dark-800 text-white font-bold py-3 px-8 rounded-md hover:bg-dark-700 transition-colors"
          >
            I Have an Account
          </Link>
        </div>
        
        <style>{`
          @keyframes fade-in-down {
            0% {
              opacity: 0;
              transform: translateY(-20px);
            }
            100% {
              opacity: 1;
              transform: translateY(0);
            }
          }
          @keyframes fade-in-up {
            0% {
              opacity: 0;
              transform: translateY(20px);
            }
            100% {
              opacity: 1;
              transform: translateY(0);
            }
          }
          .animate-fade-in-down {
            animation: fade-in-down 0.5s ease-out forwards;
          }
          .animate-fade-in-up {
            opacity: 0;
            animation: fade-in-up 0.5s ease-out forwards;
          }
        `}</style>
      </main>
    </div>
  );
};

export default LandingPage;
